-- I am checking how many tables we have and their types
SELECT * FROM INFORMATION_SCHEMA.TABLES


SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_products'


-- Explore all the countries our customers from

SELECT DISTINCT country
FROM gold.dim_customers

-- DIMENSION EXPLORATION
-- Explote all the product categories 'The major Divisions'
SELECT DISTINCT category, sub_category, product_name
FROM gold.dim_products


-- Explore Dates

SELECT min(order_date) as first_order_date,-- First order date
       max(order_date) as last_order_date, -- Last Order date  
       DATEDIFF(Year, min(order_date), max(order_date)) as ord_range_years
FROM gold.fact_sales


SELECT
     MIN(birthdate) as oldest_cust,
     MAX(birthdate) as youngest_cust
FROM gold.dim_customers


-- Exploration of Big numbers

-- Find the Total Sales
SELECT SUM(sales_amount) as total_sales FROM gold.fact_sales;

-- Find how many items are sold
SELECT sum(quantity) as total_sales_quantity
FROM gold.fact_sales

-- Find the average selling price   
SELECT AVG(price) as avg_sales_price
FROM gold.fact_sales

-- Find the total num of orders
SELECT count(distinct order_number) as num_of_orders FROM gold.fact_sales

-- Find the total num of products
SELECT count( product_key) as num_of_products FROM gold.dim_products


-- Find the total num of customers
SELECT count(distinct customer_id) as num_of_customers FROM gold.dim_customers


-- Find the total num of customers that has pplaced an order
SELECT count(distinct customer_key) as num_of_customers
FROM gold.fact_sales;


-- Generate Report to show all the key metrics of the business

SELECT 'Total Sales' as measure_name, SUM(sales_amount) as measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' as measure_name, SUM(quantity) as measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' as measure_name, AVG(price) as avg_sales_price FROM gold.fact_sales
UNION ALL 
SELECT 'Total nr. orders' as measure_name, COUNT(distinct order_number) as num_of_orders FROM gold.fact_sales
UNION ALL
SELECT 'Total nr. products' as measure_name, COUNT( product_key) as num_of_products FROM gold.dim_products
UNION ALL
SELECT 'Total nr. customers' as measure_name, COUNT(distinct customer_id) as num_of_customers FROM gold.dim_customers



-- Magnitude Analysis
-- Find total customers by country
SELECT country,
       COUNT(customer_key) as num_of_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY num_of_customers DESC

-- Find total customers by gender
SELECT gender,
       COUNT(customer_key) as num_of_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY num_of_customers DESC

-- Find total products by category
SELECT category
       ,COUNT(product_key) as num_of_prod
FROM gold.dim_products
GROUP BY category
ORDER BY 2 DESC

-- Find the avg cost for each category
SELECT category,
       AVG(cost) as avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY 2 DESC

-- Find the total revenue generated for each category
SELECT pr.category,
       SUM(sales_amount) as total_rev 
FROM gold.fact_sales as sl
LEFT JOIN gold.dim_products as pr
       ON pr.product_key = sl.product_key
GROUP BY pr.category
ORDER BY total_rev DESC;

 -- Find the total revenue generated by each customer

SELECT  cs.customer_key,
        cs.first_name,
        cs.last_name,
        SUM(sl.sales_amount) as total_sales
FROM gold.fact_sales as sl
LEFT JOIN gold.dim_customers as cs
       ON cs.customer_key = sl.customer_key
GROUP BY cs.customer_key,
         cs.first_name,
         cs.last_name
ORDER BY total_sales DESC

-- Find the total rev generated by countries
SELECT  cs.country,
        SUM(sl.sales_amount) as total_sales
FROM gold.fact_sales as sl
LEFT JOIN gold.dim_customers as cs
       ON cs.customer_key = sl.customer_key
GROUP BY cs.country
ORDER BY total_sales DESC

-- What is the distribution of sold items across countries
SELECT  cs.country,
        SUM(sl.quantity) as sold_items_quantity
FROM gold.fact_sales as sl
LEFT JOIN gold.dim_customers as cs
       ON cs.customer_key = sl.customer_key
GROUP BY cs.country
ORDER BY sold_items_quantity DESC


-- Which 5 products generate the highest revenue?

SELECT TOP 5 
       pr.sub_category,
       SUM(sales_amount) as total_rev   
FROM gold.fact_sales as sl
LEFT JOIN gold.dim_products as pr
       ON pr.product_key = sl.product_key
GROUP BY pr.sub_category
ORDER BY total_rev DESC


-- WHICH 5 products generate the lowest revenue
SELECT TOP 5 
       pr.product_name,
       SUM(sales_amount) as total_rev   
FROM gold.fact_sales as sl
LEFT JOIN gold.dim_products as pr
       ON pr.product_key = sl.product_key
GROUP BY pr.product_name
ORDER BY total_rev ASC


-- Creating  Ranking with Window functions
SELECT 
    product_name,
    total_rev
FROM 
    (SELECT 
           pr.product_name,
           SUM(sales_amount) as total_rev,
           ROW_NUMBER() OVER (ORDER BY SUM(sales_amount) DESC) as rank_products
    FROM gold.fact_sales as sl
    LEFT JOIN gold.dim_products as pr
           ON pr.product_key = sl.product_key
    GROUP BY pr.product_name) t
WHERE rank_products <= 5


-- Find the top 10 customers who have generated the highest revenue
SELECT  TOP 10 
        cs.first_name,
        cs.last_name,
        SUM(sl.sales_amount) as total_sales
FROM gold.fact_sales as sl
LEFT JOIN gold.dim_customers as cs
       ON cs.customer_key = sl.customer_key

GROUP BY cs.first_name,
         cs.last_name
ORDER BY total_sales DESC

-- with window fucntions  TOP 10 
SELECT
    first_name,
    total_sales,
    order_sales
FROM 
    (SELECT  
            cs.first_name,
            cs.last_name,
            SUM(sl.sales_amount) as total_sales,
            ROW_NUMBER() OVER(ORDER BY SUM(sl.sales_amount) DESC) as order_sales
    FROM gold.fact_sales as sl
    LEFT JOIN gold.dim_customers as cs
           ON cs.customer_key = sl.customer_key
    GROUP BY cs.first_name,
             cs.last_name)t
WHERE order_sales <= 5
